version: 2

models:
  - name: stg_claims
    columns:
      - name: claim_id
        tests: [not_null, unique]
      - name: member_id
        tests: [not_null]
      - name: amount
        tests: [not_null]
      - name: claim_status
        tests:
          - accepted_values:
              values: ['PAID', 'DENIED', 'PENDING']
  - name: fct_claims
    columns:
      - name: claim_id
        tests: [not_null, unique]
